version: '3.8'

services:
  ubuntu-service:
    image: ubuntu:22.04 #ваш образ не пулился
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 500M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.labels.SERVERTYPE == worker
      labels:
        - "com.docker.swarm.logging.driver=json-file"
        - "com.docker.swarm.logging.options.max-size=5m"
        - "com.docker.swarm.logging.options.max-file=1"
    environment:
      - HOSTNAME={{.Node.Hostname}}
    networks:
      - mts-coord-db-planning-postgres
      - mts-coord-ds-test-redis-nowidows-net
    command: ["sh", "-c", "sleep infinity"] # уже после делал apt-get install -y postgresql-client redis-tools
    volumes:
      - ubuntu-service-logs:/var/log

  postgres:   # подключался из контейнера убунты psql -h 10.0.1.7 -U test -d test_db
    image: postgres:latest
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.SERVERTYPE == worker
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      HOSTNAME: {{.Node.Hostname}}
    networks:
      - mts-coord-db-planning-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:   # подключался из контейнера убунты redis-cli -h 10.0.2.7
    image: redis:latest
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.SERVERTYPE == worker
    environment:
      HOSTNAME: {{.Node.Hostname}}
    networks:
      - mts-coord-ds-test-redis-nowidows-net
    volumes:
      - redis-data:/data

networks:
  mts-coord-db-planning-postgres:
    driver: overlay
  mts-coord-ds-test-redis-nowidows-net:
    driver: overlay

volumes:
  ubuntu-service-logs:
  postgres-data:
  redis-data:
