---
# tasks file for swarm
- name: Использование пароля для входа по ssh - запрещено
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify:
    - restart sshd

- name: Заходить под пользователем root - запрещено
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'
    state: present
    backup: yes
  notify: restart sshd

- name: Установка необходимого софта
  apt:
    name:
      - mc
      - ncdu
      - cifs-utils
      - nfs-common
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
    
- name: Добавление официальных gpg ключей
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Добавление репозитория докера
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Аптейд кеша
  apt:
    update_cache: yes

- name: Установка докера версии 20.10.21
  shell: sudo apt install docker-ce={{ VERSION_STRING }} docker-ce-cli={{ VERSION_STRING }} containerd.io docker-buildx-plugin docker-compose-plugin -y
  become: true

- name: Запуск докера и установка автозапуска
  service:
    name: docker
    state: started
    enabled: yes

- name: Добавление пользователей
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: sudo
    append: yes
  loop:
    - admin-1
    - admin-2
    - admin-3
    - ansible
    - autodeploy

- name: Доступ по ключам ssh
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '/home/alex/.ssh/id_rsa.pub') }}"
  loop:
    - admin-1
    - admin-2
    - admin-3
    - ansible
    - autodeploy

- name: Добавление пользователей в группу докер
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop:
    - admin-1
    - admin-2
    - admin-3
    - ansible
    - autodeploy